(function() {var implementors = {};
implementors["kernel"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kernel/heap_allocator/struct.HoleInfo.html\" title=\"struct kernel::heap_allocator::HoleInfo\">HoleInfo</a>",synthetic:false,types:["kernel::heap_allocator::HoleInfo"]},];
implementors["log"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"log/enum.Level.html\" title=\"enum log::Level\">Level</a>",synthetic:false,types:["log::Level"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"log/enum.LevelFilter.html\" title=\"enum log::LevelFilter\">LevelFilter</a>",synthetic:false,types:["log::LevelFilter"]},];
implementors["x86_64"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"x86_64/memory/paging/entry/struct.EntryFlags.html\" title=\"struct x86_64::memory::paging::entry::EntryFlags\">EntryFlags</a>",synthetic:false,types:["x86_64::memory::paging::entry::EntryFlags"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"x86_64/memory/paging/frame/struct.Frame.html\" title=\"struct x86_64::memory::paging::frame::Frame\">Frame</a>",synthetic:false,types:["x86_64::memory::paging::frame::Frame"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"x86_64/memory/paging/page/struct.Page.html\" title=\"struct x86_64::memory::paging::page::Page\">Page</a>",synthetic:false,types:["x86_64::memory::paging::page::Page"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"x86_64/memory/struct.PhysicalAddress.html\" title=\"struct x86_64::memory::PhysicalAddress\">PhysicalAddress</a>",synthetic:false,types:["x86_64::memory::physical_address::PhysicalAddress"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"x86_64/memory/struct.VirtualAddress.html\" title=\"struct x86_64::memory::VirtualAddress\">VirtualAddress</a>",synthetic:false,types:["x86_64::memory::virtual_address::VirtualAddress"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
